# Generated by Django 4.1.1 on 2022-12-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_profile_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
